<?php

namespace ylaakel\BilleterieBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
	public function commandesDate($date) {
		$qb = $this->createQueryBuilder('c')
				   ->where('c.laDate = :date')
    			   ->setParameter('date', $date);

		$query = $qb->getQuery();

 		$results = $query->getResult();

 		return $results;
	}
}
