<?php

namespace ylaakel\BilleterieBundle\Repository;

/**
 * InfoBilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoBilletRepository extends \Doctrine\ORM\EntityRepository
{
}
